### PR TITLE
Diagram continue

### PR DESCRIPTION
**Pull request by efekeremaydin**
getClass().getSimpleName() methods

### CODE REVIEW

**Comment by efekeremaydin** [comment]
hey @Hushtarr  can you check this out pls

**Comment by efekeremaydin** [comment]
added a new note for testing  // new note

**Review by Hushtarr — APPROVED** [review]

**Comment by efekeremaydin** [comment]
Cheers mate

**Comment by Hushtarr** [comment]
Github operation is really cool,we need more practice

**Pull request merged**
