### PR TITLE
Added an OOP folder

### PR DESCRIPTION
**Pull request by efekeremaydin**
Created Inheritance file

### CODE REVIEW

**Comment by efekeremaydin** [comment]
can you overview and merge? @Hushtarr

**Comment by efekeremaydin** [comment]
also not sure how do we easily add screenshots in the files?

**Comment by Hushtarr** [comment]
yes bro, i can view the content,but not the type

**Comment by efekeremaydin** [comment]
hi @Hushtarr  did you add this to the repo, i can't see?

**Pull request merged**
